version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - .:/app
      - uploads:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped
    command: flask run --host=0.0.0.0 --port=5000 --debug

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
  uploads: